spring:
  application:
    name: coding-app-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/coding_app_db
    username: postgres
    password: behruzbek787
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

logging:
  level:
    com.codingapp: DEBUG